name: Build Windows
on:
  workflow_dispatch:

jobs:
  build-windows:
    name: Build Windows MSVC Release
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "x86_64 release"
            runner: windows-2022
            arch: x86_64
            buildtype: release

    runs-on: ${{matrix.runner}}

    steps:

      - name: Set prefix path
        shell: bash
        run: |
          echo "prefix_path_backslash=c:\strawberry_msvc_${{matrix.arch}}_${{matrix.buildtype}}" >> $GITHUB_ENV
          echo "prefix_path_forwardslash=c:/strawberry_msvc_${{matrix.arch}}_${{matrix.buildtype}}" >> $GITHUB_ENV
          echo "prefix_path_unix=/c/strawberry_msvc_${{matrix.arch}}_${{matrix.buildtype}}" >> $GITHUB_ENV

      - name: Set cmake buildtype
        shell: bash
        run: echo "cmake_buildtype=$(echo ${{matrix.buildtype}} | sed 's/.*/\u&/')" >> $GITHUB_ENV

      - name: Show SDK versions
        shell: bash
        run: |
          for i in "/c/Program Files (x86)/Windows Kits/10/Include/"*; do
            basename $i
          done

      - name: Set SDK version
        if: matrix.arch == 'x86_64'
        shell: bash
        run: echo "WINDOWSSDKDIR=C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0" >> $GITHUB_ENV

      - name: Set SDK version
        if: matrix.arch == 'arm64'
        shell: bash
        run: echo "WINDOWSSDKDIR=C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0" >> $GITHUB_ENV

      - name: Install rsync
        shell: cmd
        run: choco install rsync

      - name: Cleanup PATH
        uses: egor-tensin/cleanup-path@v5

      - name: Create downloads directory
        shell: bash
        run: mkdir -p downloads

      - name: Download Windows MSVC dependencies
        shell: bash
        run: |
          url="https://files.strawberrymusicplayer.org/windows/dependencies/msvc/${{matrix.arch}}"
          filename="strawberry-windows-msvc-${{matrix.arch}}-dependencies.tar.xz"
          curl -f -L -z "downloads/${filename}" -o "downloads/${filename}" "${url}/${filename}"

      - name: Extract Windows MSVC dependencies
        shell: bash
        run: tar -C /c -x -f "downloads/strawberry-windows-msvc-${{matrix.arch}}-dependencies.tar.xz"

      - name: Update PATH
        shell: bash
        run: echo "${{env.prefix_path_forwardslash}}/bin" >> $GITHUB_PATH

      - name: Copy bin files
        shell: bash
        run: |
          if [ -d "${{env.prefix_path_forwardslash}}/bin_${{matrix.buildtype}}" ]; then
            cp -v -f -R -u "${{env.prefix_path_forwardslash}}/bin_${{matrix.buildtype}}/"* "${{env.prefix_path_forwardslash}}/bin/"
          fi

      - name: Delete conflicting files
        shell: bash
        run: |
          if [ -d "${{env.prefix_path_forwardslash}}/bin" ]; then
            rm -v -f "${{env.prefix_path_forwardslash}}/bin/libcrypto-3.dll"
            rm -v -f "${{env.prefix_path_forwardslash}}/bin/libssl-3.dll"
          fi

      - name: Delete conflicting icu
        shell: bash
        run: |
          if [ -d "${{env.prefix_path_forwardslash}}/bin" ]; then
            rm -v -f "${{env.prefix_path_forwardslash}}/bin/icu"*.dll
          fi

      - name: Download NSIS LockedList plugin
        shell: bash
        run: |
          url="https://files.strawberrymusicplayer.org/windows/nsis"
          filename="nsis-lockedlist-plugin.zip"
          curl -f -L -z "downloads/${filename}" -o "downloads/${filename}" "${url}/${filename}"

      - name: Extract NSIS LockedList plugin
        shell: bash
        run: 7z -y x "downloads/nsis-lockedlist-plugin.zip" -o"downloads/nsis-lockedlist-plugin"

      - name: Download NSIS Registry plugin
        shell: bash
        run: |
          url="https://files.strawberrymusicplayer.org/windows/nsis"
          filename="nsis-registry-plugin.zip"
          curl -f -L -z "downloads/${filename}" -o "downloads/${filename}" "${url}/${filename}"

      - name: Extract NSIS Registry plugin
        shell: bash
        run: 7z -y x "downloads/nsis-registry-plugin.zip" -o"downloads/nsis-registry-plugin"

      - name: Download NSIS Inetc plugin
        shell: bash
        run: |
          url="https://files.strawberrymusicplayer.org/windows/nsis"
          filename="nsis-inetc-plugin.zip"
          curl -f -L -z "downloads/${filename}" -o "downloads/${filename}" "${url}/${filename}"

      - name: Extract NSIS Inetc plugin
        shell: bash
        run: 7z -y x "downloads/nsis-inetc-plugin.zip" -o"downloads/nsis-inetc-plugin"

      - name: Install NSIS plugins
        shell: bash
        run: |
          cp -v -f "downloads/nsis-lockedlist-plugin/Plugins/x86-unicode/LockedList.dll" "/c/Program Files (x86)/NSIS/Plugins/x86-unicode/"
          cp -v -f "downloads/nsis-registry-plugin/Plugins/x86-unicode/Registry.dll" "/c/Program Files (x86)/NSIS/Plugins/x86-unicode/"
          cp -v -f "downloads/nsis-inetc-plugin/Plugins/x86-unicode/INetC.dll" "/c/Program Files (x86)/NSIS/Plugins/x86-unicode/"

      - name: Setup MSVC Environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{matrix.arch}}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Create Build Environment
        shell: bash
        run: |
          mkdir -p build
          echo "CL=/MP" >> $GITHUB_ENV

      - name: Set ENABLE_WIN32_CONSOLE
        shell: bash
        run: |
          if [ "${{matrix.buildtype}}" = "debug" ]; then
            echo "ENABLE_WIN32_CONSOLE=ON" >> $GITHUB_ENV
          else
            echo "ENABLE_WIN32_CONSOLE=OFF" >> $GITHUB_ENV
          fi

      - name: Set ENABLE_SPOTIFY
        shell: bash
        run: |
          if [ "${{secrets.SPOTIFY_API_CLIENT_ID}}" != "" ] && [ "${{secrets.SPOTIFY_API_CLIENT_SECRET}}" != "" ]; then
            echo "ENABLE_SPOTIFY=ON" >> $GITHUB_ENV
          else
            echo "ENABLE_SPOTIFY=OFF" >> $GITHUB_ENV
          fi

      - name: Generate API credentials encryption key
        shell: bash
        run: |
          key=$(head -c 64 /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | head -c 32)
          echo "API_CREDENTIALS_ENCRYPTION_KEY=${key}" >> $GITHUB_ENV

      - name: Remove -lm from .pc files
        shell: bash
        run: |
          for f in "${{env.prefix_path_forwardslash}}/lib/pkgconfig/"*.pc; do
            sed -i 's/-lm//g' "$f"
          done

      - name: Run CMake
        shell: bash
        working-directory: build
        run: |
          cmake \
            -G "Ninja" \
            -DCMAKE_INSTALL_PREFIX="${{env.prefix_path_forwardslash}}" \
            -DCMAKE_PREFIX_PATH="${{env.prefix_path_forwardslash}}" \
            -DCMAKE_BUILD_TYPE="${{env.cmake_buildtype}}" \
            -DBUILD_WITH_QT6=ON \
            -DUSE_MSVC=ON \
            -DMSVC_BUILD_TYPE="${{matrix.buildtype}}" \
            -DMSVC_ARCH="${{matrix.arch}}" \
            -DENABLE_WIN32_CONSOLE=${{env.ENABLE_WIN32_CONSOLE}} \
            -DENABLE_SPOTIFY=${{env.ENABLE_SPOTIFY}} \
            -DENABLE_ENCRYPTED_API_CREDENTIALS=ON \
            -DAPI_CREDENTIALS_ENCRYPTION_KEY="${{env.API_CREDENTIALS_ENCRYPTION_KEY}}" \
            -DSPOTIFY_API_CLIENT_ID="${{secrets.SPOTIFY_API_CLIENT_ID}}" \
            -DSPOTIFY_API_CLIENT_SECRET="${{secrets.SPOTIFY_API_CLIENT_SECRET}}" \
            ..

      - name: Run Make
        shell: bash
        working-directory: build
        run: cmake --build .

      - name: Copy extra binaries
        shell: bash
        working-directory: build
        run: |
          if [ -d "${{env.prefix_path_forwardslash}}/bin_extra" ]; then
            cp -v -f -R -u "${{env.prefix_path_forwardslash}}/bin_extra/"* "${{env.prefix_path_forwardslash}}/bin/"
          fi

      - name: Create directories
        shell: bash
        working-directory: build
        run: |
          mkdir -p gio-modules
          mkdir -p imageformats
          mkdir -p gstreamer-1.0
          mkdir -p platforms
          mkdir -p sqldrivers
          mkdir -p styles
          mkdir -p tls

      - name: Copy GIO modules
        shell: bash
        working-directory: build
        run: cp -v -f "${{env.prefix_path_forwardslash}}/lib/gio/modules/"*.dll gio-modules/

      - name: Copy Qt platform plugins
        shell: bash
        working-directory: build
        run: cp -v -f "${{env.prefix_path_forwardslash}}/plugins/platforms/"*.dll platforms/

      - name: Copy Qt styles
        shell: bash
        working-directory: build
        run: cp -v -f "${{env.prefix_path_forwardslash}}/plugins/styles/"*.dll styles/

      - name: Copy Qt TLS plugins
        shell: bash
        working-directory: build
        run: cp -v -f "${{env.prefix_path_forwardslash}}/plugins/tls/"*.dll tls/

      - name: Copy Qt SQL drivers
        shell: bash
        working-directory: build
        run: cp -v -f "${{env.prefix_path_forwardslash}}/plugins/sqldrivers/qsqlite.dll" sqldrivers/

      - name: Copy Qt imageformats plugins
        shell: bash
        working-directory: build
        run: cp -v -f "${{env.prefix_path_forwardslash}}/plugins/imageformats/qjpeg.dll" imageformats/

      - name: Copy gstreamer plugins
        shell: bash
        working-directory: build
        run: cp -v -f "${{env.prefix_path_forwardslash}}/lib/gstreamer-1.0/"*.dll gstreamer-1.0/

      - name: Download copydlldeps.sh
        shell: bash
        working-directory: build
        run: |
          url="https://raw.githubusercontent.com/strawberrymusicplayer/strawberry-msvc-build-tools/master"
          filename="copydlldeps.sh"
          curl -f -L -z "${filename}" -o "${filename}" "${url}/${filename}"

      - name: Copy dependencies
        shell: bash
        working-directory: build
        run: bash copydlldeps.sh -b "${{env.prefix_path_forwardslash}}/bin" -p "${{env.prefix_path_forwardslash}}" -s /c/strawberry_msvc_x86_64 -a ${{matrix.arch}} strawberry.exe

      - name: Copy nsis files
        shell: bash
        working-directory: build
        run: cp -v -f ../dist/windows/*.nsh .

      - name: Copy COPYING license file
        shell: bash
        working-directory: build
        run: cp -v -f ../COPYING .

      - name: List files
        shell: bash
        working-directory: build
        run: ls -l -a

      - name: Check that all files are included in nsi
        shell: bash
        working-directory: build
        run: |
          files_missing=""
          for f in $(find . -maxdepth 1 -name '*.dll'); do
            f_base=$(basename "${f}")
            if ! grep -q "${f_base}" strawberry.nsi; then
              files_missing="${files_missing} ${f_base}"
            fi
          done
          if ! [ "${files_missing}" = "" ]; then
            echo "Files missing in nsi: ${files_missing}"
            exit 1
          fi

      - name: Download MSVC runtime
        shell: bash
        working-directory: build
        run: curl -f -O -L https://aka.ms/vc14/vc_redist.x64.exe

      - name: Create nsis installer
        shell: cmd
        working-directory: build
        run: makensis strawberry.nsi

      - name: Upload Strawberry Installer Artifact
        uses: actions/upload-artifact@v4
        with:
          name: StrawberrySetup-x64-Release
          path: build/StrawberrySetup*.exe
